## Introduction to NumPy

NumPy is shorthand for "Numeric Python." NumPy allows you to produce a high-performance multidimensional array object and contains many efficient functions for computation on matrices and arrays. The NumPY data structure produces an array of uniform values, and runs faster than the standard Python list as a result.

In [3]:
import numpy as np

## Vectors and Matrices

### Vectors

We can create vectors using `np.array`.

In [4]:
I = np.array([1, 0, 0])
J = np.array([0, 1, 0])
K = np.array([0, 0, 1])

These are "row" vectors, but they can be easily transformed into "column" vectors.

In [5]:
I[:, np.newaxis]

array([[1],
       [0],
       [0]])

### Matrices

Let's use `np.array` to create a matrix (in this case a [Pascal matrix](https://en.wikipedia.org/wiki/Pascal_matrix)).

In [6]:
L4 = np.array([[1, 0, 0, 0],
               [1, 1, 0, 0],
               [1, 2, 1, 0],
               [1, 3, 3, 1]])

In [7]:
L4

array([[1, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 2, 1, 0],
       [1, 3, 3, 1]])

### Accessing Elements

To access a single cell, supply both row and column indices.

In [8]:
L4[0, 0]

1

To retrieve a row just use a single index.

In [9]:
L4[1]

array([1, 1, 0, 0])

In [18]:
L4[-1]

array([1, 3, 3, 1])

To retrieve a column, use `:` for the row index.

In [10]:
L4[:,2]

array([0, 0, 1, 3])

In [19]:
L4[:2,:2]

array([[1, 0],
       [1, 1]])

In [23]:
L4[:4,::2]

array([[1, 0],
       [1, 0],
       [1, 1],
       [1, 3]])

In [11]:
print(np.array([0,2]))

[0 2]


We can use a vector as a set of indices for slicing a matrix.

In [12]:
indices = np.array([0, 2])

In [13]:
L4[indices]

array([[1, 0, 0, 0],
       [1, 2, 1, 0]])

In [14]:
L4[:,indices]

array([[1, 0],
       [1, 0],
       [1, 1],
       [1, 3]])

### Dimensions and Shape

In [15]:
L4.shape

(4, 4)

In [16]:
L4.ndim

2

In [17]:
L4.size

16

Shape shows the dimension of the array, ndim is the number of dimensions, size shows the total size of the array.

In [36]:
L4.reshape(2, 8)

array([[1, 0, 0, 0, 1, 1, 0, 0],
       [1, 2, 1, 0, 1, 3, 3, 1]])

Collapses the rows and extends the columns

### Transposing and Splitting

In [29]:
upperL4, lowerL4 = np.vsplit(L4, [2])
print(upperL4)
print(lowerL4)

[[1 0 0 0]
 [1 1 0 0]]
[[1 2 1 0]
 [1 3 3 1]]


In [28]:
leftL4, rightL4 = np.hsplit(L4, [2])
print(leftL4)
print(rightL4)

[[1 0]
 [1 1]
 [1 2]
 [1 3]]
[[0 0]
 [0 0]
 [1 0]
 [3 1]]


In [27]:
L4.T

array([[1, 1, 1, 1],
       [0, 1, 2, 3],
       [0, 0, 1, 3],
       [0, 0, 0, 1]])

Flips the rows and columns

## Generating Data: Sequences

Using `np.linspace` you can generate a uniform sequence of numbers. The result is a (row) vector.

In [37]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

The third argument is not the step size: it's the number of elements in the sequence.

## Generating Data: Random Numbers

For the purposes of reproducibility, always set a seed.

In [38]:
rnd = np.random.RandomState(seed = 13)

# This will always produce the same matrix of random numbers (regardless of when it is executed or on what machine!)
#
rnd.uniform(size=(5, 5))

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 , 0.97260111],
       [0.45344925, 0.60904246, 0.77552651, 0.64161334, 0.72201823],
       [0.03503652, 0.29844947, 0.05851249, 0.85706094, 0.37285403],
       [0.67984795, 0.25627995, 0.34758122, 0.00941277, 0.35833378],
       [0.94909418, 0.21789901, 0.31939137, 0.91777239, 0.03190367]])

In [39]:
from scipy.linalg import pascal

In [40]:
pascal(4, kind='lower')

array([[1, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 2, 1, 0],
       [1, 3, 3, 1]], dtype=uint64)